services:
  postgres:
    image: postgres
    container_name: postgres-url-shortener
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: urlShortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urlShortener_network

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"   # UI Web
      - "14268:14268"   # HTTP collector
      - "14250:14250"   # gRPC collector
      - "6831:6831/udp" # UDP (opcional, usado por agentes)
    networks:
      - urlShortener_network

volumes:
  postgres_data:

networks:
  urlShortener_network:
    driver: bridge
